# Site settings
title: Sounds of Germany
locale: uk
partner:
  name: Germany National Tourism Board
  link: "https://www.germany.travel/en/index.html"

description: >
  To mark the 250th birthday of one of the greatest musical composers of all-time, Beethoven, we’re celebrating the anniversary by immersing ourselves in the sounds of Germany - a symphony that would have sparked Beethoven’s creativity. Since travel plans have been on hold until now, the anniversary celebrations will continue into 2021, giving you even more reason to travel to Germany.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/germany" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/germany/_assets/img"
css:     "/uk/2020/germany/_assets/css"
js:      "/uk/2020/germany/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed